name: Build and Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - name: Upload
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage/lcov.info
